// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHoIy0_B-CeRLBHR1f3WnZwPWvcWEbxxc',
    appId: '1:364766041367:web:09b28243bdbd1f766b9352',
    messagingSenderId: '364766041367',
    projectId: 'corona-lms-cc0db',
    authDomain: 'corona-lms-cc0db.firebaseapp.com',
    storageBucket: 'corona-lms-cc0db.firebasestorage.app',
    measurementId: 'G-D10FF7WH9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSNgjTLqKz0AtPL20MG6gJNbP-EfijT1Q',
    appId: '1:364766041367:android:7c80a93f0ce003b46b9352',
    messagingSenderId: '364766041367',
    projectId: 'corona-lms-cc0db',
    storageBucket: 'corona-lms-cc0db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmRCpCpDRbV48uKiKWADa5tHZPeKCpkZo',
    appId: '1:364766041367:ios:4ba1b251eef2f4116b9352',
    messagingSenderId: '364766041367',
    projectId: 'corona-lms-cc0db',
    storageBucket: 'corona-lms-cc0db.firebasestorage.app',
    iosBundleId: 'com.example.coronaLmsWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmRCpCpDRbV48uKiKWADa5tHZPeKCpkZo',
    appId: '1:364766041367:ios:4ba1b251eef2f4116b9352',
    messagingSenderId: '364766041367',
    projectId: 'corona-lms-cc0db',
    storageBucket: 'corona-lms-cc0db.firebasestorage.app',
    iosBundleId: 'com.example.coronaLmsWebapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHoIy0_B-CeRLBHR1f3WnZwPWvcWEbxxc',
    appId: '1:364766041367:web:0449ddeb1534a0336b9352',
    messagingSenderId: '364766041367',
    projectId: 'corona-lms-cc0db',
    authDomain: 'corona-lms-cc0db.firebaseapp.com',
    storageBucket: 'corona-lms-cc0db.firebasestorage.app',
    measurementId: 'G-9CB0RPY340',
  );
}
